### ISSUE TITLE
Firefox not surfing in internet

### ISSUE THREAD

**Issue by Schwitzd** [danielguerra69/alpine-xfce4-xrdp#2]
Dear Daniel,
I downloaded the whole repository and built the image all is working as expect except for Firefox...
It is not surfing in internet... seems a networking issue

Any idea?
Thx a lot

**Comment by danielguerra69** [comment]
Do you have an internet connection ? Firefox needs enough memory, run docker with : --shm-size 1g

**Comment by Schwitzd** [comment]
I have an internet connection.
If I pull the image from the docker hub all is working as expected.
But if i download the package from github, build the image then I have the error...

G4rp

**Comment by danielguerra69** [comment]
Confirmed, I have the same problem. Wget works fine. I thought its firefox-esr but chromium-browser has the same problem. I tried alpine:3.8 and everything works fine again. I commited a fix
